# Generated by Django 5.0a1 on 2023-10-28 11:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('study', '0004_useranswer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='useranswer',
            options={'verbose_name': 'ответ_пользователя', 'verbose_name_plural': 'ответы_пользователя'},
        ),
    ]
